unpackaged/objects/WW_Event__c.object
<CustomObject>
    <description>This holds the information of the place, time and details of the event</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <label>Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_3__c</fullName>
        <label>Address 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Andhra Pradesh</fullName>
                </value>
                <value>
                    <fullName>Arunachal Pradesh</fullName>
                </value>
                <value>
                    <fullName>Bihar</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Karnataka</fullName>
                </value>
                <value>
                    <fullName>Kerala</fullName>
                </value>
                <value>
                    <fullName>Madhya Pradesh</fullName>
                </value>
                <value>
                    <fullName>Maharastra</fullName>
                </value>
                <value>
                    <fullName>Orissa</fullName>
                </value>
                <value>
                    <fullName>Tamil Nadu</fullName>
                </value>
                <value>
                    <fullName>Telangana</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WW_Event_Date__c</fullName>
        <description>Date on which the event takes place</description>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/WW_EventDetails__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>WW_Event__c</referenceTo>
        <relationshipLabel>EventDetails</relationshipLabel>
        <relationshipName>EventDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EventDetails</relationshipLabel>
        <relationshipName>EventDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EventDetails</label>
    <nameField>
        <displayFormat>WW-{000}</displayFormat>
        <label>Event Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/WW_EventsController.cls
public class WW_EventsController {
	@auraEnabled
    public static List<WW_Event__c> getUpcomingEventDetails(){
        List<WW_Event__c> lstUpcomingEvents = new List<WW_Event__c>();
        lstUpcomingEvents = [Select id, name, WW_Event_Date__c, Address_1__c, 
                             Address_2__c, Address_3__c, City__c, State__c 
                             From WW_Event__c where WW_Event_Date__c > TODAY];
        return lstUpcomingEvents;
    }
    
    @auraEnabled
    public static List<String> getAllEventDetails(){
        String volunteerId = '0014S000002fZ4pQAE';
        List<WW_EventDetails__c> lstEventDetails = [Select id, name, Event__c, Volunteer__c From 
                                                   WW_EventDetails__c Where Volunteer__c =: volunteerId];
        Set<String> idEventDetails = new Set<String>();
        List<WW_Event__c> lstRegisteredEvents;
        List<WW_Event__c> lstUpcomingEvents = getUpcomingEventDetails();
        List<String> retVal = new List<String>();
        if(lstEventDetails != null && !lstEventDetails.isEmpty()){
            for(WW_EventDetails__c eventDetail : lstEventDetails){
                idEventDetails.add(eventDetail.Event__c);
            }
            lstRegisteredEvents = [Select id, name, WW_Event_Date__c, Address_1__c, 
                             Address_2__c, Address_3__c, City__c, State__c 
                             From WW_Event__c where id IN: idEventDetails];
        }
        retVal.add(JSON.serialize(lstUpcomingEvents));
        retVal.add(JSON.serialize(lstRegisteredEvents));
        return retVal;
    }
}